import type { Metadata } from "next";
import "./globals.css";
import Nav from "@/components/nav";
import { ThemeProvider } from "@/components/theme-provider";

export const metadata: Metadata = {
  title: "Unigrow",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider attribute="class" disableTransitionOnChange>
          <div className="flex min-h-screen flex-col">
            <Nav />
            <div className="mt-16 flex-1 p-10">{children}</div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
