import { Department } from "@/lib/types";

export const departmentMapper: { [code: string]: string } = {
  AAI: "Applied Artificial Intelligence",
  ACC: "Accounting",
  BIA: "Business Intelligence and Analytics",
  BIO: "Biology",
  BIOE: "Bioengineering",
  BME: "Biomedical Engineering",
  BT: "Business and Technology",
  CAL: "College of Arts Letters",
  CE: "Civil Engineering",
  CH: "Chemistry",
  CHE: "Chemical Engineering",
  CLK: "Clark Scholars",
  CM: "Construction Management",
  COMM: "Professional Communications",
  CPE: "Computer Engineering",
  CS: "Computer Science",
  DE: "Developmental English",
  DS: "Data Science",
  ECON: "Economics",
  EE: "Electrical Engineering",
  ELC: "English Language and Communication",
  EM: "Engineering Management",
  EMT: "Executive Management of Technology",
  EN: "Environmental Engineering",
  ENGR: "Interdepartmental Engineering",
  ES: "Enterprise Systems",
  FA: "Financial Analytics",
  FE: "Financial Engineering",
  FIN: "Finance",
  GEN: "General Elective",
  HAR: "HumanitiesArt",
  HHS: "HumanitiesHistory",
  HLI: "HumanitiesLiterature",
  HMU: "HumanitiesMusic",
  HONR: "Honor Program",
  HPL: "HumanitiesPhilosophy",
  HSS: "HumanitiesSocial Sciences",
  HST: "Humanities Science and Technology Studies",
  HTH: "HumanitiesTheater",
  HUM: "Humanities General",
  IDE: "Innovation Design and Entrepreneurship",
  IPD: "Integrated Product Development",
  ISE: "Industrial and Systems Engineering",
  LCH: "Language Chinese",
  LFR: "Language French",
  LSP: "Language Spanish",
  LTL: "LanguageItalian",
  MA: "Mathematics",
  ME: "Mechanical Engineering",
  MGT: "Management",
  MIS: "Information Systems",
  MT: "Materials Engineering",
  NANO: "Nanotechnology",
  NE: "Naval Engineering",
  NIS: "Networked Information Systems",
  OE: "Ocean Engineering",
  PAE: "Product Architecture and Engineering",
  PEP: "Physics Engineering Physics",
  PIN: "Pinnacle Scholar",
  PME: "Pharmaceutical Manufacturing",
  QF: "Quantitative Finance",
  SEF: "Science Engineering Found for Edu",
  SES: "Systems Engineering Security",
  SM: "Sustainability Management",
  SOC: "Service Oriented Computing",
  SSW: "Software Engineering",
  SYS: "Systems Engineering",
  TE: "Technical Elective",
  TG: "Technogenesis",
  TM: "Telecommunications Management"
};

export const departmentList: Department[] = [
  { course_code: "AAI", department: "Applied Artificial Intelligence" },
  { course_code: "ACC", department: "Accounting" },
  { course_code: "BIA", department: "Business Intelligence and Analytics" },
  { course_code: "BIO", department: "Biology" },
  { course_code: "BIOE", department: "Bioengineering" },
  { course_code: "BME", department: "Biomedical Engineering" },
  { course_code: "BT", department: "Business and Technology" },
  { course_code: "CAL", department: "College of Arts Letters" },
  { course_code: "CE", department: "Civil Engineering" },
  { course_code: "CH", department: "Chemistry" },
  { course_code: "CHE", department: "Chemical Engineering" },
  { course_code: "CLK", department: "Clark Scholars" },
  { course_code: "CM", department: "Construction Management" },
  { course_code: "COMM", department: "Professional Communications" },
  { course_code: "CPE", department: "Computer Engineering" },
  { course_code: "CS", department: "Computer Science" },
  { course_code: "DE", department: "Developmental English" },
  { course_code: "DS", department: "Data Science" },
  { course_code: "ECON", department: "Economics" },
  { course_code: "EE", department: "Electrical Engineering" },
  { course_code: "ELC", department: "English Language and Communication" },
  { course_code: "EM", department: "Engineering Management" },
  { course_code: "EMT", department: "Executive Management of Technology" },
  { course_code: "EN", department: "Environmental Engineering" },
  { course_code: "ENGR", department: "Interdepartmental Engineering" },
  { course_code: "ES", department: "Enterprise Systems" },
  { course_code: "FA", department: "Financial Analytics" },
  { course_code: "FE", department: "Financial Engineering" },
  { course_code: "FIN", department: "Finance" },
  { course_code: "GEN", department: "General Elective" },
  { course_code: "HAR", department: "HumanitiesArt" },
  { course_code: "HHS", department: "HumanitiesHistory" },
  { course_code: "HLI", department: "HumanitiesLiterature" },
  { course_code: "HMU", department: "HumanitiesMusic" },
  { course_code: "HONR", department: "Honor Program" },
  { course_code: "HPL", department: "HumanitiesPhilosophy" },
  { course_code: "HSS", department: "HumanitiesSocial Sciences" },
  {
    course_code: "HST",
    department: "Humanities Science and Technology Studies"
  },
  { course_code: "HTH", department: "HumanitiesTheater" },
  { course_code: "HUM", department: "Humanities General" },
  {
    course_code: "IDE",
    department: "Innovation Design and Entrepreneurship"
  },
  { course_code: "IPD", department: "Integrated Product Development" },
  { course_code: "ISE", department: "Industrial and Systems Engineering" },
  { course_code: "LCH", department: "Language Chinese" },
  { course_code: "LFR", department: "Language French" },
  { course_code: "LSP", department: "Language Spanish" },
  { course_code: "LTL", department: "LanguageItalian" },
  { course_code: "MA", department: "Mathematics" },
  { course_code: "ME", department: "Mechanical Engineering" },
  { course_code: "MGT", department: "Management" },
  { course_code: "MIS", department: "Information Systems" },
  { course_code: "MT", department: "Materials Engineering" },
  { course_code: "NANO", department: "Nanotechnology" },
  { course_code: "NE", department: "Naval Engineering" },
  { course_code: "NIS", department: "Networked Information Systems" },
  { course_code: "OE", department: "Ocean Engineering" },
  { course_code: "PAE", department: "Product Architecture and Engineering" },
  { course_code: "PEP", department: "Physics Engineering Physics" },
  { course_code: "PIN", department: "Pinnacle Scholar" },
  { course_code: "PME", department: "Pharmaceutical Manufacturing" },
  { course_code: "QF", department: "Quantitative Finance" },
  { course_code: "SEF", department: "Science Engineering Found for Edu" },
  { course_code: "SES", department: "Systems Engineering Security" },
  { course_code: "SM", department: "Sustainability Management" },
  { course_code: "SOC", department: "Service Oriented Computing" },
  { course_code: "SSW", department: "Software Engineering" },
  { course_code: "SYS", department: "Systems Engineering" },
  { course_code: "TE", department: "Technical Elective" },
  { course_code: "TG", department: "Technogenesis" },
  { course_code: "TM", department: "Telecommunications Management" }
];
